### ISSUE TITLE
[VnV] Traceability Matrix 

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#15]
@gabrielasd, I find it is hard a little bit to follow your traceability matrix table as the elements weren't referenced. 
Also, I have a question related to **R6**, and **Reusable** as they are not covered within the **requirements**, Is that correct?
![issue5](https://user-images.githubusercontent.com/31176105/97891967-7038b400-1cfd-11eb-858a-20665fd9a6d7.PNG)

**Comment by tingyuw** [comment]
I have the same questions here. I think it would be better if you cover all the requirements mentioned in the SRS, since one of the goals of the VnV plan is to verify the SRS.

**Comment by gabrielasd** [comment]
Hello @moalaa and @tingyuw,
I'll add hyperlinks for the system tests for clarity of this table.
You are right about the "Reusable" nonfunctional requirement, I'll add a system test that addresses it. My reasoning to let it uncovered at this point was that I thought I would refer to it when the unit tests section was completed, given that it depends on the modularity of the code. I see now that is not correct.

In regards to the functional requirement R6 from the SRS, this is what it states:
![SRS_req6](https://user-images.githubusercontent.com/26312264/98178391-a37c6e00-1eca-11eb-81c3-af322dd8a4a8.png)
Because I don't think I can come up for a test for this, I left it uncovered.

**Comment by gabrielasd** [comment]
Fixed in commit 1e8e526b22262c7a88e12ed50e381297bed1b4ec
