### ISSUE TITLE
[VnV] Question related to SRS Questionnaire

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#17]
Hello @gabrielasd, I liked what you done in **SRS Questionnaire** section, and the way you assign each question to your verification team. :+1:
I have a question, may be Dr. @smiths can help in answering it,
Should the verification team answer these questions, or it is just a way of faking the process? If yes, how should it be done?

![issue8](https://user-images.githubusercontent.com/31176105/97898664-2bfde180-1d06-11eb-91fa-3ea536c90d6a.PNG)

**Comment by gabrielasd** [comment]
Hi @moalaa,
thank you :) I actually borrowed the ideas from previus students of the course.

Regarding the questionnaire, ideally, I should have prepared it when I submitted the SRS first draft or have assigned similar questions as issues to you and the other reviewers instead of just asking to review my SRS :(. Actually, I tried to include in the questions some of the corrections and suggestions you had made. So I would say that I'm faking the process.
Though I understand it is unlikely the case, if you had time to do a second review and found new errors, you could add them as new issues.
