### ISSUE TITLE
Test input-value

### ISSUE THREAD

**Issue by tingyuw** [gabrielasd/eomee#19]
For this test case, I have a similar opinion as to the first test case. You only provide variables in the table, but for a test case verifying values, maybe it would be better if you provide specific value in your document. You can still provide the table of input definition, which is great, but you can also create another table for specific input values, and the type of error output it generates. For example, you can put the description of each test cases in the table instead of in the test case derivation, I think it might be more understandable. Also, I don't think you need to detail those input definitions, such as the numpy.random code, the test team only needs to know what kind of input I can feed and what is the expected output. That was my opinion :)

**Comment by gabrielasd** [comment]
Hi @tingyuw 
Thanks for the comments :), I agree with most of them and I'll address them in a commit.

However, I didn't understand the following two comments:
- "You only provide variables in the table, but for a test case verifying values, maybe it would be better if you provide specific value in your document."
-"I don't think you need to detail those input definitions, such as the numpy.random code, the test team only needs to know what kind of input I can feed and what is the expected output."

I wanted to provide specific values for the variables in the table so that those be used in the tests (cases S1-S5) that's why I added the variables definitions (immage below)
![test_values](https://user-images.githubusercontent.com/26312264/98188440-011bb500-1ee1-11eb-9214-ef28d3da2735.png)

The reason for using random generated numbers is that for the purposes of all but the last test case, I only care about the shape of the arrays/matrices. The EOMEE code will expect/check the variables from collumn 1 in the table to have certain shapes and dimensions and complain raising a value error exception (as indicated by the Output) if these requirement is not meet. The test cases described in the table look at producing this error message to be raised.

**Comment by tingyuw** [comment]
@gabrielasd 
Sorry for the late reply, I just saw your comment. 
What I mean for providing specific value is that including value like 0.5 and 1 instead of just showing the numpy.random. I know that you will use numpy.random to generate each parameter, but I was suggesting that you could include some specific values in the test cases so it will be much clearer for readers. But if you think it is better to do it this way for your case, then just leave it as it is. : )

**Comment by gabrielasd** [comment]
These tests were removed from the final VnV document (commit 1e8e526b22262c7a88e12ed50e381297bed1b4ec)
